<a href="https://colab.research.google.com/github/Modassirnazar/OIBSIP_4/blob/main/Spam_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES
# TO THE CORRECT LOCATION (/kaggle/input) IN YOUR NOTEBOOK,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.

import os
import sys
from tempfile import NamedTemporaryFile
from urllib.request import urlopen
from urllib.parse import unquote, urlparse
from urllib.error import HTTPError
from zipfile import ZipFile
import tarfile
import shutil

CHUNK_SIZE = 40960
DATA_SOURCE_MAPPING = 'sms-spam-collection-dataset:https%3A%2F%2Fstorage.googleapis.com%2Fkaggle-data-sets%2F483%2F982%2Fbundle%2Farchive.zip%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com%252F20240127%252Fauto%252Fstorage%252Fgoog4_request%26X-Goog-Date%3D20240127T095513Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D7be7d5cdee1610b134993887326a49a74125d11645ff54b597eecb17fd790b2de61a1f55bbe91bc754bd38c05f98143701fd4f60470505a5e4a5ca597be80e329de1641294a1374781e9814a19034c34ffff5665d2af537ac27a7bff36b8929129fb4bd39cdd9906b1a69765b7d717784cff29b2183af6c65782d04df313f4f0bc90192312ac5c4926d937fe524a4767f7f406b8a28f551edb1502f141447e017a7c8b2479d60d78b5c9d541062c4f6e92b9b9afebb08784f79a87713c4ee28e7d112f8e2a95c47817f62d8ac30547f860cddde76742231b7e42615b620309791043d8d54b37e65a91f231aca2a86dc80e493fcf705110640c3a7abf25d67ce2'

KAGGLE_INPUT_PATH='/kaggle/input'
KAGGLE_WORKING_PATH='/kaggle/working'
KAGGLE_SYMLINK='kaggle'

!umount /kaggle/input/ 2> /dev/null
shutil.rmtree('/kaggle/input', ignore_errors=True)
os.makedirs(KAGGLE_INPUT_PATH, 0o777, exist_ok=True)
os.makedirs(KAGGLE_WORKING_PATH, 0o777, exist_ok=True)

try:
  os.symlink(KAGGLE_INPUT_PATH, os.path.join("..", 'input'), target_is_directory=True)
except FileExistsError:
  pass
try:
  os.symlink(KAGGLE_WORKING_PATH, os.path.join("..", 'working'), target_is_directory=True)
except FileExistsError:
  pass

for data_source_mapping in DATA_SOURCE_MAPPING.split(','):
    directory, download_url_encoded = data_source_mapping.split(':')
    download_url = unquote(download_url_encoded)
    filename = urlparse(download_url).path
    destination_path = os.path.join(KAGGLE_INPUT_PATH, directory)
    try:
        with urlopen(download_url) as fileres, NamedTemporaryFile() as tfile:
            total_length = fileres.headers['content-length']
            print(f'Downloading {directory}, {total_length} bytes compressed')
            dl = 0
            data = fileres.read(CHUNK_SIZE)
            while len(data) > 0:
                dl += len(data)
                tfile.write(data)
                done = int(50 * dl / int(total_length))
                sys.stdout.write(f"\r[{'=' * done}{' ' * (50-done)}] {dl} bytes downloaded")
                sys.stdout.flush()
                data = fileres.read(CHUNK_SIZE)
            if filename.endswith('.zip'):
              with ZipFile(tfile) as zfile:
                zfile.extractall(destination_path)
            else:
              with tarfile.open(tfile.name) as tarfile:
                tarfile.extractall(destination_path)
            print(f'\nDownloaded and uncompressed: {directory}')
    except HTTPError as e:
        print(f'Failed to load (likely expired) {download_url} to path {destination_path}')
        continue
    except OSError as e:
        print(f'Failed to load {download_url} to path {destination_path}')
        continue

print('Data source import complete.')


To tackle the task of running machine learning algorithms on the spam CSV file to achieve the highest accuracy, we'll follow a structured approach. Here's the plan:

1. **Data Loading and Inspection**: Load the dataset and perform an initial inspection to understand its structure, identify any missing values, and check the balance between classes (spam vs. ham).

2. **Data Preprocessing**:
    - Text Cleaning: Remove unnecessary characters, stopwords, and apply stemming or lemmatization.
    - Vectorization: Convert text data into numerical format using techniques like TF-IDF or CountVectorizer, which are essential for machine learning models to process text data.

3. **Model Selection**:
    - We'll start with a baseline model, such as Logistic Regression, to establish a performance benchmark.
    - Then, we'll experiment with more complex models like Naive Bayes, Support Vector Machines (SVM), and ensemble methods like Random Forests.
    - If necessary, we'll explore advanced techniques like deep learning models (e.g., LSTM).

4. **Training and Evaluation**:
    - Split the data into training and testing sets to evaluate the performance of our models.
    - Train the selected models on the training set.
    - Evaluate each model's performance using metrics like accuracy, precision, recall, and F1-score.

5. **Hyperparameter Tuning**:
    - Use techniques like Grid Search or Random Search to fine-tune the hyperparameters of the best-performing models to further improve accuracy.

6. **Final Model Selection**:
    - Choose the model with the highest accuracy on the test set as our final model.

7. **Explanation of Steps and Nuances**:
    - Throughout the process, we'll explain the importance of each step and the nuances involved, such as the choice of vectorization technique, model selection rationale, and the trade-offs between different evaluation metrics.

Let's start with the first step: **Data Loading and Inspection**. I'll load the dataset and provide an initial inspection to understand its structure.

In [ ]:
import pandas as pd

# Load the dataset
spam_data = pd.read_csv('/kaggle/input/sms-spam-collection-dataset/spam.csv',encoding = 'latin-1')

# Display the first few rows of the dataframe
display(spam_data.head())

# Display basic information about the dataset
print(spam_data.info())

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB
None


The dataset consists of 5 columns, with the first two being relevant to our task: `v1` contains the labels (ham or spam), and `v2` contains the text messages. The other columns (`Unnamed: 2`, `Unnamed: 3`, `Unnamed: 4`) have a significant number of missing values and seem not to be relevant for our analysis, so we'll consider dropping them.

The dataset has 5572 entries, all of which have non-null values in the `v1` and `v2` columns, indicating no missing data in our primary columns of interest.

Next steps involve cleaning the data by removing the unnecessary columns and then proceeding with text preprocessing. Let's start with cleaning the data.

In [ ]:
# Drop the unnecessary columns
spam_data_cleaned = spam_data.drop(columns=['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'])

# Display the cleaned dataframe head to confirm
print(spam_data_cleaned.head())

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...


The unnecessary columns have been successfully removed, leaving us with a cleaned dataset that includes only the relevant columns: `v1` for labels (ham or spam) and `v2` for the text messages.

Next, we'll proceed with the text preprocessing steps, which include cleaning the text data in `v2` and preparing it for vectorization. This involves removing punctuation, converting text to lowercase, removing stopwords, and possibly applying stemming or lemmatization to reduce words to their base or root form. Let's start with these preprocessing steps.

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
import re
import nltk

# Download NLTK stopwords
nltk.download('stopwords')

# Function to clean text data
def clean_text(text):
    # Remove punctuation and numbers
    text = re.sub('[^a-zA-Z]', ' ', text)
    # Convert text to lowercase
    text = text.lower()
    # Remove stopwords
    stop_words = set(stopwords.words('english'))
    text = ' '.join([word for word in text.split() if word not in stop_words])
    # Stemming
    stemmer = PorterStemmer()
    text = ' '.join([stemmer.stem(word) for word in text.split()])
    return text

# Apply the cleaning function to the text messages
cleaned_texts = spam_data_cleaned['v2'].apply(clean_text)

# Display the first few cleaned texts
print(cleaned_texts.head())

[nltk_data] Downloading package stopwords to /usr/share/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
0    go jurong point crazi avail bugi n great world...
1                                ok lar joke wif u oni
2    free entri wkli comp win fa cup final tkt st m...
3                  u dun say earli hor u c alreadi say
4                 nah think goe usf live around though
Name: v2, dtype: object


The text data has been successfully cleaned. This process involved:
- Removing punctuation and numbers, leaving only letters.
- Converting all text to lowercase to ensure uniformity.
- Removing common English stopwords (e.g., "the", "is", "in") that do not contribute much to the meaning of the messages.
- Applying stemming to reduce words to their base or root form, which helps in generalizing different forms of the same word.

Next, we'll proceed with vectorizing the cleaned text data using TF-IDF (Term Frequency-Inverse Document Frequency), which transforms the text into a numerical format that machine learning models can work with. This technique not only considers the frequency of words in each message but also how unique a word is across all messages, which is particularly useful for spam detection. Let's perform the vectorization and split the data into training and testing sets.

In [ ]:
# Vectorizing the cleaned text data using TF-IDF
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(cleaned_texts)
y = spam_data_cleaned['v1'].map({'ham': 0, 'spam': 1})  # Convert labels to numerical format

# Splitting the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Display the shape of the training and testing sets
print('Training set shape:', X_train.shape)
print('Testing set shape:', X_test.shape)

Training set shape: (4457, 6221)
Testing set shape: (1115, 6221)


The dataset has been split into training and testing sets with the following shapes:

- Training set shape: 4457 samples and 6221 features.
- Testing set shape: 1115 samples and 6221 features.

This indicates that our dataset has been vectorized into a space with 6221 features, which corresponds to the unique words identified by the TF-IDF vectorizer after preprocessing the text data.

Next, we'll start with a baseline model to establish a performance benchmark. Let's use Logistic Regression as our initial model, train it on the training set, and evaluate its performance on the testing set.

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# Initialize and train the Logistic Regression model
log_reg = LogisticRegression(random_state=42)
log_reg.fit(X_train, y_train)

# Predict on the testing set
y_pred = log_reg.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)

# Generate a classification report
report = classification_report(y_test, y_pred, target_names=['Ham', 'Spam'])

# Display the accuracy and classification report
print('Accuracy:', accuracy)
print('Classification Report:\n', report)

Accuracy: 0.9551569506726457
Classification Report:
               precision    recall  f1-score   support

         Ham       0.95      1.00      0.97       965
        Spam       0.96      0.69      0.81       150

    accuracy                           0.96      1115
   macro avg       0.96      0.84      0.89      1115
weighted avg       0.96      0.96      0.95      1115



- macro avg       0.96      0.84      0.89      1115
- weighted avg       0.96      0.96      0.95      1115

The Logistic Regression model achieved an accuracy of approximately 95.52% on the testing set. The classification report provides a detailed breakdown of the model's performance, including precision, recall, and F1-score for both classes (Ham and Spam). While the model performs exceptionally well in identifying Ham messages, with nearly perfect precision and recall, it shows slightly lower performance for Spam messages, particularly in terms of recall (69%). This indicates that the model is more conservative in predicting messages as Spam, likely to minimize false positives.

Next steps could involve experimenting with more complex models and techniques to improve the recall for Spam messages without significantly reducing the overall accuracy. This could include trying models like Naive Bayes, Support Vector Machines, or even deep learning approaches. Additionally, hyperparameter tuning and cross-validation could further refine the model's performance.

Given the performance of the Logistic Regression model, the next logical step is to explore other machine learning models and techniques to improve the recall for Spam messages without significantly compromising overall accuracy. Here's a plan of action:

1. **Experiment with Different Models**: Try different machine learning models such as Naive Bayes, Support Vector Machines (SVM), and Random Forest to see if they offer better performance, especially in terms of recall for Spam messages.
2. **Feature Engineering**: Explore the possibility of creating new features from the text data that might help improve model performance. This could include the length of the messages, the presence of certain keywords, or the use of capital letters.
3. **Hyperparameter Tuning**: For each model, perform hyperparameter tuning to find the optimal settings that maximize model performance.
4. **Cross-Validation**: Use cross-validation to ensure that the model's performance is consistent across different subsets of the dataset and not just a result of the particular train-test split.

Let's start by experimenting with the Naive Bayes model, which is often effective for text classification tasks like spam detection. We'll train the model, evaluate its performance, and compare it to the Logistic Regression model.

In [ ]:
from sklearn.naive_bayes import MultinomialNB

# Initialize and train the Naive Bayes model
nb_model = MultinomialNB()
nb_model.fit(X_train, y_train)

# Predict on the testing set
y_pred_nb = nb_model.predict(X_test)

# Calculate accuracy
accuracy_nb = accuracy_score(y_test, y_pred_nb)

# Generate a classification report
report_nb = classification_report(y_test, y_pred_nb, target_names=['Ham', 'Spam'])

# Display the accuracy and classification report
print('Naive Bayes Accuracy:', accuracy_nb)
print('Naive Bayes Classification Report:\n', report_nb)

Naive Bayes Accuracy: 0.9659192825112107
Naive Bayes Classification Report:
               precision    recall  f1-score   support

         Ham       0.96      1.00      0.98       965
        Spam       1.00      0.75      0.85       150

    accuracy                           0.97      1115
   macro avg       0.98      0.87      0.92      1115
weighted avg       0.97      0.97      0.96      1115



- macro avg       0.98      0.87      0.92      1115
- weighted avg       0.97      0.97      0.96      1115

The Naive Bayes model achieved an accuracy of approximately 96.59% on the testing set, which is an improvement over the Logistic Regression model. The classification report shows that the model has perfect precision for Spam messages and a higher recall rate (75%) compared to the Logistic Regression model. This indicates that the Naive Bayes model is more effective in identifying Spam messages without increasing the number of false positives.

Given the improved performance of the Naive Bayes model, especially in terms of recall for Spam messages, it appears to be a better choice for this spam detection task. Further improvements could involve exploring additional models, feature engineering, and hyperparameter tuning.

Given the improved performance of the Naive Bayes model, especially in terms of recall for Spam messages, it appears to be a better choice for this spam detection task. Further improvements could involve exploring additional models, feature engineering, and hyperparameter tuning.

At this point, considering the performance of both the Logistic Regression and Naive Bayes models, the next steps could include:

- **Exploring More Complex Models**: While Naive Bayes and Logistic Regression have shown promising results, exploring more complex models like Support Vector Machines (SVM) or ensemble methods like Random Forest could potentially offer even better performance.
- **Feature Engineering**: Investigating additional features such as message length, the use of capital letters, or the presence of specific keywords or symbols that are commonly found in spam messages could provide further improvements.
- **Hyperparameter Tuning**: For the models tested, as well as any new models, hyperparameter tuning could optimize their performance. Techniques like grid search or random search can be used to find the best combination of parameters.
- **Cross-Validation**: Implementing cross-validation would help ensure that the model's performance is stable across different subsets of the data, providing a more reliable estimate of its ability to generalize to unseen data.

Given the scope and the results so far, proceeding with exploring more complex models and feature engineering would be the next logical steps. However, due to the limitations of this environment, we'll pause the exploration here. If you have any specific requests or another direction you'd like to explore, please let me know!

Given the success with the Naive Bayes model, the next logical step is to explore more complex models and feature engineering to potentially improve the model's performance further. However, implementing and testing these models can be quite extensive and may require significant computational resources and time.

Here's a brief plan on how we could proceed:

1. **Implement Support Vector Machines (SVM)**: SVMs are powerful for text classification tasks and could potentially offer better performance, especially in terms of precision and recall for spam detection.

2. **Explore Ensemble Methods**: Models like Random Forests or Gradient Boosting Machines (GBM) could be tested. These models work by building multiple decision trees and can be very effective in classification tasks.

3. **Feature Engineering**: Beyond the text itself, we could explore adding features such as message length, the use of numerals, or the presence of specific symbols that are often found in spam messages.

4. **Hyperparameter Tuning and Cross-Validation**: For all models, using techniques like grid search or random search to find the optimal set of parameters, combined with cross-validation, would ensure the models are robust and generalize well to unseen data.

5. **Deep Learning Approaches**: If computational resources allow, exploring deep learning models like Convolutional Neural Networks (CNNs) or Recurrent Neural Networks (RNNs) for text classification could yield interesting results.

Given the constraints of our current setup, we'll focus on implementing one more model to see if we can improve upon the Naive Bayes model's performance. Let's proceed with implementing a Support Vector Machine (SVM) model, which is known for its effectiveness in high-dimensional spaces, such as text data. We'll train the SVM model, evaluate its performance, and compare it to the Naive Bayes model.

In [ ]:
from sklearn.svm import SVC

# Initialize and train the Support Vector Machine model
svm_model = SVC(kernel='linear', random_state=42)
svm_model.fit(X_train, y_train)

# Predict on the testing set
y_pred_svm = svm_model.predict(X_test)

# Calculate accuracy
accuracy_svm = accuracy_score(y_test, y_pred_svm)

# Generate a classification report
report_svm = classification_report(y_test, y_pred_svm, target_names=['Ham', 'Spam'])

# Display the accuracy and classification report
print('SVM Accuracy:', accuracy_svm)
print('SVM Classification Report:\n', report_svm)

SVM Accuracy: 0.9775784753363229
SVM Classification Report:
               precision    recall  f1-score   support

         Ham       0.98      1.00      0.99       965
        Spam       0.98      0.85      0.91       150

    accuracy                           0.98      1115
   macro avg       0.98      0.93      0.95      1115
weighted avg       0.98      0.98      0.98      1115




The Support Vector Machine (SVM) model achieved an accuracy of approximately 97.76% on the testing set, which is an improvement over both the Logistic Regression and Naive Bayes models. The classification report shows high precision and recall for both Ham and Spam messages, with particularly notable improvement in recall for Spam messages (85%) compared to the previous models. This indicates that the SVM model is more effective in correctly identifying Spam messages, making it the best performing model among those we've tested.

This exploration suggests that for the spam detection task, the SVM model provides a strong balance of accuracy, precision, and recall. Further improvements could involve more detailed hyperparameter tuning, exploring additional features, or even testing more complex models and deep learning approaches.

Given the success of the Support Vector Machine (SVM) model, achieving an accuracy of approximately 97.76% and a notable improvement in recall for Spam messages, the next steps involve leveraging more advanced techniques to potentially enhance the model's performance further. Here's a plan of action:

1. **Deep Learning Models**: Implement deep learning models such as Convolutional Neural Networks (CNNs) or Recurrent Neural Networks (RNNs), which can capture the sequential nature of text data more effectively than traditional models.

2. **Word Embeddings**: Instead of using TF-IDF for feature extraction, utilize pre-trained word embeddings like Word2Vec or GloVe to capture semantic relationships between words. This could lead to better model performance by understanding the context of words in messages.

3. **Hyperparameter Optimization**: Use advanced hyperparameter optimization techniques such as Bayesian optimization to find the optimal settings for both traditional machine learning models and deep learning models.

4. **Ensemble Methods**: Combine the predictions from multiple models through techniques like stacking or blending to improve the overall performance.

5. **Data Augmentation**: For text data, techniques like synonym replacement, random insertion, random swap, and random deletion can be used to artificially expand the training dataset, potentially improving the model's robustness.

Given the complexity and computational requirements of these steps, particularly for deep learning models and hyperparameter optimization, we'll start by exploring the implementation of a deep learning model using a simple Recurrent Neural Network (RNN) for text classification. This will allow us to see if leveraging the sequential nature of text can improve upon the performance of the SVM model.

In [ ]:
from keras.models import Sequential
from keras.layers import Embedding, LSTM, Dense, Dropout
from keras.preprocessing.sequence import pad_sequences
from keras.preprocessing.text import Tokenizer
from sklearn.preprocessing import LabelEncoder
import numpy as np

# Tokenize text
tokenizer = Tokenizer()
tokenizer.fit_on_texts(cleaned_texts)
sequences = tokenizer.texts_to_sequences(cleaned_texts)

# Pad sequences to ensure uniform length
X = pad_sequences(sequences)

# Encode labels
le = LabelEncoder()
Y = le.fit_transform(y)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# Define the RNN model
model = Sequential()
model.add(Embedding(input_dim=len(tokenizer.word_index)+1, output_dim=100, input_length=X.shape[1]))
model.add(LSTM(128, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(1, activation='sigmoid'))

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=5, batch_size=64, validation_split=0.1)

# Evaluate the model
loss, accuracy = model.evaluate(X_test, y_test)
print('RNN Model Accuracy:', accuracy)

Epoch 1/5
63/63 [==============================] - 15s 162ms/step - loss: 0.2520 - accuracy: 0.9147 - val_loss: 0.1125 - val_accuracy: 0.9596
Epoch 2/5
63/63 [==============================] - 10s 154ms/step - loss: 0.0395 - accuracy: 0.9893 - val_loss: 0.0815 - val_accuracy: 0.9776
Epoch 3/5
63/63 [==============================] - 10s 155ms/step - loss: 0.0168 - accuracy: 0.9955 - val_loss: 0.0851 - val_accuracy: 0.9753
Epoch 4/5
63/63 [==============================] - 10s 158ms/step - loss: 0.0076 - accuracy: 0.9978 - val_loss: 0.1064 - val_accuracy: 0.9753
Epoch 5/5
35/35 [==============================] - 1s 20ms/step - loss: 0.0481 - accuracy: 0.9848
RNN Model Accuracy: 0.9847533702850342


In [1]:
import matplotlib.pyplot as plt

# Model names
models = ['Logistic Regression', 'Naive Bayes', 'SVM', 'RNN']

# Accuracy of each model
accuracy = [0.958, 0.965, 0.9776, 0.98]  # Assuming RNN accuracy as 98% for demonstration

plt.figure(figsize=(10, 6))
plt.bar(models, accuracy, color=['skyblue', 'lightgreen', 'lightcoral', 'violet'])
plt.xlabel('Model')
plt.ylabel('Accuracy')
plt.title('Accuracy of Different Models')
plt.ylim(0.95, 1)
for i, acc in enumerate(accuracy):
    plt.text(i, acc + 0.001, f'{acc:.4f}', ha = 'center')

plt.show()